from pathlib import Path 

configfile: "config/config.yaml"

def require(arg, config=config):
    assert arg in config, f'{arg} must be specified!'
    assert config[arg] != None, f'{arg} cannot be None!'
required = ['fasta', 'bed', 'out']
[require(arg) for arg in required]

SNAKE_DIR = Path(workflow.basedir)
SCRIPT_DIR = SNAKE_DIR / "scripts"

with open(config['fasta']) as f:
    config['SAMPLES'] = [line[1:].strip() for line in f.readlines() if line.startswith('>')]

rule all:
    input:
        'heatmap.pdf',

include: "rules/align.smk"
include: "rules/bed.smk"
include: "rules/heatmap.smk"

